version: '3.8'

services:
  fastapi:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: ${SERVICE_NAME}
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    env_file:
      - ../.env
    environment:
      - DB_USER=${DB_USER}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_PASSWORD=${DB_PASSWORD}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PYTHONPATH=/app
    volumes:
      - ../src/migrations:/app/src/migrations
    networks:
      - app-network
    restart: always

  postgres:
    image: postgres:17.5
    container_name: ${SERVICE_DB_NAME}
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: always

  redis:
    image: redis:latest
    container_name: redis
    networks:
      - app-network
    restart: always

volumes:
  postgres_data:
    driver: local

networks:
  app-network:
    driver: bridge
